version: '3.4'

services:
  api:
    build: .
    environment:
      NODE_ENV: production
    restart: always
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
networks:
  default:
    external:
      name: selfhostednetwork